### ISSUE TITLE
コアハンドブック 公開タスクリスト

### ISSUE THREAD

**Issue by t-hamano** [jawordpressorg/core-handbook#192]
GitHubリポジトリ上で全てのページの翻訳が完了となったあと、日本語のコアハンドブックとして公開するために行う作業をメモしておきます。

※20223/10/21 に開催されるWordCamp Tokyo 2023までには公開したいため、各タスクの暫定スケジュールも追加。

- [x] GitHub 側の最終調整
  - [x] textlint による全体のエラーチェック、調整 #208
  - [x] コメントアウトした英文と日本語訳の間を一行空ける（今後原文を更新した時に、正確に差分が抽出されるようにするため）
  - [x] もう一度原文と同期し、差分・ページ追加があれば追加翻訳する #205
  - [x] 斜体記号を必要に応じて `「`、`」`  に置き換え #209
  - [x] 原文に存在しないが、日本語GitHubリポジトリに存在する未翻訳のページ（＝原文でページが削除されたもの）を、GitHubリポジトリからも消す。 #201
  - [x] 単語の一貫性の向上 #210
- [x] WordPress 側で、各固定ページを公開状態で作成する （ページのスラッグを確定させるため。また、デフォルトでは、Draft/下書きページを親に指定できないため）
- [x] 翻訳テキスト内のページ内リンクを、原文ではなく日本語ハンドブック内に向くように、ドメインを置換する (`https://make.wordpress.org/core/handbook` → `https://ja.wordpress.org/team/handbook/core/`) #211
- [x] WordPress 側の各固定ページに、GitHubの翻訳テキストを貼り付ける
  - [x] 特殊なレイアウト、マークダウンでは表現できないスタイルは、原文ハンドブックも考慮して適宜調整する
  - [x] 外部リンクは、新しいタブで開くように設定する
  - [x] 翻訳等のミスが見つかった場合は適宜WordPress側で修正し、GitHub側でも同様の変更を [fix/publish-sync](https://github.com/jawordpressorg/core-handbook/tree/fix/publish-sync) ブランチにコミットする。
- [x] 全ページ移行後、GitHubソースを `/#` と `(#` で検索し、アンカーリンクを抽出する。見出しのアンカーリンクはテキストから自動生成されるので、正しく紐づくようにWordPress側で変更する。GitHub側でも同様の変更を [fix/publish-sync](https://github.com/jawordpressorg/core-handbook/tree/fix/publish-sync) ブランチにコミットする。
  - #214
  - #215
- [x] [ハンドブック一覧](https://ja.wordpress.org/team/handbook/)ページにコアハンドブックを追加する
- [x] [単体で存在するブラウザサポートページ](https://ja.wordpress.org/team/handbook/browser-support/)は、[コアハンドブック内にも全く同じページがある](https://github.com/jawordpressorg/core-handbook/blob/main/core/best-practices/browser-support.md)ため、削除する。
- [ ] **(10/18)** ブログでアナウンス記事を公開する (**Note: 公開日を実際に公開した日に更新する事を忘れずに！**)
- [x] **(都度)** WordPress 側で行われた修正がコミットされている [fix/publish-sync](https://github.com/jawordpressorg/core-handbook/tree/fix/publish-sync) ブランチからPRを作成し、メインブランチにマージする。
  - #212
  - #213
  - #214
  - #215

### ブログでの告知内容

下書きとして作成済

**Comment by t-hamano** [comment]
### Props用のアカウント一覧

| GitHub ユーザー名 | WordPress.org ユーザー名 | 備考 |
|--------|--------|--------|
| [atachibana](https://github.com/atachibana) | [atachibana](https://profiles.wordpress.org/atachibana/) |
| [east-or-est](https://github.com/east-or-est) | [azuma3derive](https://profiles.wordpress.org/azuma3derive/) |
| [miminari](https://github.com/miminari) | [mimitips](https://profiles.wordpress.org/mimitips/) |
| [nano195](https://github.com/nano195) | [nano195](https://profiles.wordpress.org/nano195/) |
| [naokomc](https://github.com/naokomc) | [nao](https://profiles.wordpress.org/nao/) |
| [nukaga](https://github.com/nukaga) | [nukaga](https://profiles.wordpress.org/nukaga/) |
| [imiyake](https://github.com/imiyake) | [torikumo](https://profiles.wordpress.org/torikumo/) |

**Comment by t-hamano** [comment]
### WordPress.org Japanese Teamにハンドブックとして公開するための管理表

https://docs.google.com/spreadsheets/d/1aB8iCxetf4SRMr0Ev8FAW1KBEHLARIdZItbrz6d4AAE/edit?usp=sharing

**Comment by t-hamano** [comment]
公開タスクが全て完了したため、クローズします。
アナウンス記事：https://ja.wordpress.org/team/2023/10/10/3783/
