### ISSUE TITLE
日本語翻訳プロジェクト Tracking Issue

### ISSUE THREAD

**Issue by t-hamano** [jawordpressorg/core-handbook#6]
[プロジェクトボード](https://github.com/orgs/jawordpressorg/projects/5)

このissueは、[Core Contoributor Handbook](https://make.wordpress.org/core/handbook/)の日本語化にあたり、対象ページをリストアップし、各ページの進捗を管理するものです。
GitHubが初めての方、翻訳作業の進め方については、「[翻訳開始から提案までの流れ](https://github.com/jawordpressorg/core-handbook/wiki/%E7%BF%BB%E8%A8%B3%E9%96%8B%E5%A7%8B%E3%81%8B%E3%82%89%E6%8F%90%E6%A1%88%E3%81%BE%E3%81%A7%E3%81%AE%E6%B5%81%E3%82%8C)」でご確認下さい。

Note: ⚠️がついている計9ページは、[コーディング規約ハンドブック](https://ja.wordpress.org/team/handbook/coding-standards/)関連のページであり、[wpcs-docs](https://github.com/jawordpressorg/wpcs-docs)リポジトリで管理されているため、原文自体は翻訳する必要がありません ([See](https://github.com/jawordpressorg/core-handbook/pull/201))。

---

- [x] [Home](https://make.wordpress.org/core/handbook/) #135
- [x] [About](https://make.wordpress.org/core/handbook/about/) #34
- [x] [About > Project Organization](https://make.wordpress.org/core/handbook/about/organization/) #41
- [x] [About > Our Philosophies](https://make.wordpress.org/core/handbook/about/philosophies/) #79
- [x] [About > Communication](https://make.wordpress.org/core/handbook/about/communication/) #151
- [x] [About > How the Release Cycle Works](https://make.wordpress.org/core/handbook/about/release-cycle/) #68
- [x] [About > How the Release Cycle Works > Features as Plugins](https://make.wordpress.org/core/handbook/about/release-cycle/features-as-plugins/) #72
- [x] [About > How the Release Cycle Works > Version Numbering](https://make.wordpress.org/core/handbook/about/release-cycle/version-numbering/) #67
- [x] [About > How the Release Cycle Works > Preparing the About Page](https://make.wordpress.org/core/handbook/about/release-cycle/preparing-the-about-page/) #191
- [x] [About > How the Release Cycle Works > Updating Bundled Theme Versions](https://make.wordpress.org/core/handbook/about/release-cycle/update-bundled-themes/) #149
- [x] [About > How the Release Cycle Works > WordPress Release Team and Focus Leads](https://make.wordpress.org/core/handbook/about/release-cycle/wordpress-release-team-and-focus-leads/) #196
- [x] [About > How the Release Cycle Works > Releasing Major Versions](https://make.wordpress.org/core/handbook/about/release-cycle/releasing-major-versions/) #134
- [x] [About > How the Release Cycle Works > Releasing Minor Versions](https://make.wordpress.org/core/handbook/about/release-cycle/releasing-minor-versions/) #194
- [x] [About > How the Release Cycle Works > Releasing Beta and RC Versions](https://make.wordpress.org/core/handbook/about/release-cycle/releasing-beta-versions/) #136
- [x] [About > How the Release Cycle Works > Block Editor Release Process for Major Releases](https://make.wordpress.org/core/handbook/about/release-cycle/block-editor-release-process-for-major-releases/)
  - #160
  - #205
- [x] [About > How the Release Cycle Works > Hosting Release Parties](https://make.wordpress.org/core/handbook/about/release-cycle/hosting-release-parties/) #195
- [x] [About > Licensing & Copyright](https://make.wordpress.org/core/handbook/about/licensing/) #143
- [x] [About > Getting Started at a Contributor Day](https://make.wordpress.org/core/handbook/about/getting-started-at-a-contributor-day/) #171
- [x] [Contribute with Testing](https://make.wordpress.org/core/handbook/testing/) #8
- [x] [Contribute with Testing > Automated Testing](https://make.wordpress.org/core/handbook/testing/automated-testing/) #19
- [x] [Contribute with Testing > Automated Testing > JavaScript: QUnit](https://make.wordpress.org/core/handbook/testing/automated-testing/qunit/) #43
- [x] [Contribute with Testing > Automated Testing > PHP: PHPUnit](https://make.wordpress.org/core/handbook/testing/automated-testing/phpunit/) #202
- [x] [Contribute with Testing > Automated Testing > Writing PHP Tests](https://make.wordpress.org/core/handbook/testing/automated-testing/writing-phpunit-tests/) #206
- [x] [Contribute with Testing > Beta Testing](https://make.wordpress.org/core/handbook/testing/beta-testing/) #163
- [x] [Contribute with Testing > User Testing](https://make.wordpress.org/core/handbook/testing/user-testing/) #165
- [x] [Contribute with Testing > User Testing > Usability](https://make.wordpress.org/core/handbook/testing/user-testing/usability/) #141
- [x] [Contribute with Testing > Reporting Bugs](https://make.wordpress.org/core/handbook/testing/reporting-bugs/) #153
- [x] [Contribute with Testing > Reporting Security Vulnerabilities](https://make.wordpress.org/core/handbook/testing/reporting-security-vulnerabilities/) #187
- [x] [Contribute with Testing > Bug Gardening](https://make.wordpress.org/core/handbook/testing/bug-gardening/) #188
- [x] [Contribute with Testing > Testing a Patch](https://make.wordpress.org/core/handbook/testing/patch/) #164
- [x] [Contribute with Testing > Write a Call for Testing](https://make.wordpress.org/core/handbook/testing/write-a-call-for-testing/) #142
- [x] [Contribute with Code](https://make.wordpress.org/core/handbook/contribute/) #16
- [x] [Contribute with Code > Code Refactoring](https://make.wordpress.org/core/handbook/contribute/code-refactoring/) #20
- [x] [Contribute with Code > The Code Repository (Git)](https://make.wordpress.org/core/handbook/contribute/git/) #28
- [x] [Contribute with Code > The Code Repository (Git) > GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) #22
- [x] [Contribute with Code > The WordPress Codebase](https://make.wordpress.org/core/handbook/contribute/codebase/) #61
- [x] [Contribute with Code > The Code Repository (SVN)](https://make.wordpress.org/core/handbook/contribute/svn/) #37
- [x] [Contribute with Code > The Code Repository (SVN) > Researching Code History](https://make.wordpress.org/core/handbook/contribute/svn/code-history/) #46
- [x] [Contribute with Code > The Bug Tracker (Trac)](https://make.wordpress.org/core/handbook/contribute/trac/) #101
- [x] [Contribute with Code > The Bug Tracker (Trac) > Trac Workflow Keywords](https://make.wordpress.org/core/handbook/contribute/trac/keywords/) #58
- [x] [Contribute with Code > Design Decisions](https://make.wordpress.org/core/handbook/contribute/design-decisions/) #81
- [x] [Contribute with Code > Fixing Bugs](https://make.wordpress.org/core/handbook/contribute/fixing-bugs/) #80
- [x] [Contribute with Docs](https://make.wordpress.org/core/handbook/docs/) #51
- [x] [Contribute with Docs > Inline Docs](https://make.wordpress.org/core/handbook/docs/inline/) #84
- [x] [Contribute with Docs > Inline Docs > JavaScript Docs](https://make.wordpress.org/core/handbook/docs/inline/js/) #84
- [x] [Contribute with Docs > Inline Docs > JavaScript Docs > Closed JS docs file tickets](https://make.wordpress.org/core/handbook/docs/inline/js/closed-tickets/) #84
- [x] [Contribute with Docs > Inline Docs > JavaScript Docs > In-progress JS docs file tickets](https://make.wordpress.org/core/handbook/docs/inline/js/in-progress-tickets/) #84
- [x] [Contribute with Docs > Inline Docs > JavaScript Docs > Unclaimed files](https://make.wordpress.org/core/handbook/docs/inline/js/unclaimed-files/) #84
- [x] [Best Practices](https://make.wordpress.org/core/handbook/best-practices/) #40
- [x] [Best Practices > Post & Comment Guidelines](https://make.wordpress.org/core/handbook/best-practices/post-comment-guidelines/) #60
- [x] ⚠️ [Best Practices > WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) #201
- [x] ⚠️ [Best Practices > WordPress Coding Standards > PHP Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/) #201
- [x] ⚠️ [Best Practices > WordPress Coding Standards > Accessibility Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/accessibility-coding-standards/) #201
- [x] ⚠️ [Best Practices > WordPress Coding Standards > CSS Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/) #201
- [x] ⚠️ [Best Practices > WordPress Coding Standards > HTML Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/html/) #201
- [x] ⚠️ [Best Practices > WordPress Coding Standards > JavaScript Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/) #201
- [x] ⚠️ [Best Practices > Inline Documentation Standards](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/) #201
- [x] ⚠️ [Best Practices > Inline Documentation Standards > PHP Documentation Standards](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/) #201
- [x] ⚠️ [Best Practices > Inline Documentation Standards > JavaScript Documentation Standards](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/javascript/) #201
- [x] [Best Practices > Workflows & Tools](https://make.wordpress.org/core/handbook/best-practices/tools/) #129
- [x] [Best Practices > Browser support](https://make.wordpress.org/core/handbook/best-practices/browser-support/) #2 
- [x] [Best Practices > Core APIs](https://make.wordpress.org/core/handbook/best-practices/core-apis/) #186
- [x] [Best Practices > Spelling](https://make.wordpress.org/core/handbook/best-practices/spelling/) #193
- [x] [Best Practices > Internationalization](https://make.wordpress.org/core/handbook/best-practices/internationalization/) #5 
- [x] [Best Practices > Writing Patches](https://make.wordpress.org/core/handbook/best-practices/writing-patches/) #152
- [x] [Best Practices > Commit Messages](https://make.wordpress.org/core/handbook/best-practices/commit-messages/) #199
- [x] [Best Practices > Backporting Commits](https://make.wordpress.org/core/handbook/best-practices/backporting-commits/) #159
- [x] [Best Practices > When you become a committer](https://make.wordpress.org/core/handbook/best-practices/when-you-become-a-committer/) #150
- [x] [Tutorials & Guides](https://make.wordpress.org/core/handbook/tutorials/) #50
- [x] [Tutorials & Guides > FAQ for New Contributors](https://make.wordpress.org/core/handbook/tutorials/faq-for-new-contributors/) #189
- [x] [Tutorials & Guides > Getting Started](https://make.wordpress.org/core/handbook/tutorials/getting-started/) #185
- [x] [Tutorials & Guides > Navigating the Community](https://make.wordpress.org/core/handbook/tutorials/navigating-the-community/) #207
- [x] [Tutorials & Guides > Installing WordPress Locally](https://make.wordpress.org/core/handbook/tutorials/installing-wordpress-locally/) #96
- [x] [Tutorials & Guides > Installing WordPress Locally > Installing from a Zip File](https://make.wordpress.org/core/handbook/tutorials/installing-wordpress-locally/from-zip/) #97
- [x] [Tutorials & Guides > Installing WordPress Locally > Installing via SVN](https://make.wordpress.org/core/handbook/tutorials/installing-wordpress-locally/from-svn/) #103
- [x] [Tutorials & Guides > Installing a Local Server](https://make.wordpress.org/core/handbook/tutorials/installing-a-local-server/) #102
- [x] [Tutorials & Guides > Installing a Local Server > Installing VVV](https://make.wordpress.org/core/handbook/tutorials/installing-a-local-server/installing-vvv/) #104
- [x] [Tutorials & Guides > Installing a Local Server > Installing DesktopServer](https://make.wordpress.org/core/handbook/tutorials/installing-a-local-server/desktopserver/) #117
- [x] [Tutorials & Guides > Installing a Local Server > Installing MAMP](https://make.wordpress.org/core/handbook/tutorials/installing-a-local-server/mamp/) #105
- [x] [Tutorials & Guides > Installing a Local Server > Installing WampServer](https://make.wordpress.org/core/handbook/tutorials/installing-a-local-server/wampserver/) #108
- [x] [Tutorials & Guides > Installing a Local Server > Installing XAMPP](https://make.wordpress.org/core/handbook/tutorials/installing-a-local-server/xampp/) #107
- [x] [Tutorials & Guides > Installing a Version Control System](https://make.wordpress.org/core/handbook/tutorials/installing-a-vcs/) #106
- [x] [Tutorials & Guides > Working with Patches](https://make.wordpress.org/core/handbook/tutorials/working-with-patches/) #204
- [x] [Tutorials & Guides > Working with Trac](https://make.wordpress.org/core/handbook/tutorials/trac/) #118
- [x] [Tutorials & Guides > Working with Trac > New User Quick Start Guide](https://make.wordpress.org/core/handbook/tutorials/trac/new-user-quick-start/) #119
- [x] [Tutorials & Guides > Working with Trac > Opening a Ticket](https://make.wordpress.org/core/handbook/tutorials/trac/opening-a-ticket/) #120
- [x] [Tutorials & Guides > Working with Trac > Submitting a Patch](https://make.wordpress.org/core/handbook/tutorials/trac/submitting-a-patch/) #121
- [x] [Tutorials & Guides > Coordinating Devchat](https://make.wordpress.org/core/handbook/tutorials/coordinating-devchat/) #125
- [x] [Tutorials & Guides > Core Team Rep Election Process](https://make.wordpress.org/core/handbook/tutorials/core-team-rep-election-process/) #127
- [x] [Tutorials & Guides > Running New Contributor Meetings](https://make.wordpress.org/core/handbook/tutorials/running-new-contributor-meetings/) #126
- [x] [Tutorials & Guides > Writing developer notes](https://make.wordpress.org/core/handbook/tutorials/writing-developer-notes/) #76
- [x] [Tutorials & Guides > Publishing the Field Guide](https://make.wordpress.org/core/handbook/tutorials/publishing-the-field-guide/) #144
- [x] [Tutorials & Guides > Leading Bug Scrubs](https://make.wordpress.org/core/handbook/tutorials/leading-bug-scrubs/) #172
- [x] [References](https://make.wordpress.org/core/handbook/references/) #48
- [x] [References > Keeping up with Gutenberg: Index 2023](https://make.wordpress.org/core/handbook/references/keeping-up-with-gutenberg-index/) #111
- [x] [References > Keeping up with Gutenberg: Index 2023 > Gutenberg Index 2020](https://make.wordpress.org/core/handbook/references/keeping-up-with-gutenberg-index/keeping-up-with-gutenberg-index-2020/) #111
- [x] [References > Keeping up with Gutenberg: Index 2023 > Gutenberg Index 2021](https://make.wordpress.org/core/handbook/references/keeping-up-with-gutenberg-index/keeping-up-with-gutenberg-index-2021/) #111
- [x] [References > Keeping up with Gutenberg: Index 2023 > Gutenberg Index 2022](https://make.wordpress.org/core/handbook/references/keeping-up-with-gutenberg-index/keeping-up-with-gutenberg-index-2022/) #111
- [x] [References > PHP Compatibility and WordPress Versions](https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/) #70
- [x] [References > PHPUnit Compatibility and WordPress Versions](https://make.wordpress.org/core/handbook/references/phpunit-compatibility-and-wordpress-versions/) #166
- [x] [Credits](https://make.wordpress.org/core/handbook/credits/) #24
- [x] [Glossary](https://make.wordpress.org/core/handbook/glossary/) #197

**Comment by t-hamano** [comment]
最初に、[Contribute with Code](https://make.wordpress.org/core/handbook/contribute/)の前半の翻訳を対応したいと思います。

- #10 
- #11 
- #12 
- #13

**Comment by osamunize** [comment]
操作に慣れる意味も含めて、クレジットのページを翻訳してみます。（実質2行だけですが）
- [ ] 翻訳: /core/handbook/credits/

**Comment by imiyake** [comment]
About > Our Philosophies 　興味があります。訳してみたいです。どうぞよろしくお願いいたします。

**Comment by imiyake** [comment]
すみません。まずは、もう少し短いところ探します。About > Our Philosophies はキャンセルさせてください

**Comment by t-hamano** [comment]
Update: #99での原文更新により、 以下ページが追加されました。

core\tutorials\core-team-rep-election-process.md

**Comment by t-hamano** [comment]
2023年内に日本語ハンドブックを公開すると仮定した場合の、毎月の進捗目標概算:

- 1月: 35/90 完了
- 2月: 40/90 完了 
- 3月: 46/90 完了
- 4月: 50/90 完了
- 5月: 56/90 完了
- 6月: 62/90 完了
- 7月: 66/90 完了
- 8月: 72/90 完了
- 9月: 78/90 完了
- 10月: 84/90 完了
- 11月: 90/90 完了
- 12月: WordPressサイトに記事登録、内部リンク書き換え、リリース 🎉

**Comment by t-hamano** [comment]
Update: #109 での原文更新により、 以下ページが追加されました。

- [References > Keeping up with Gutenberg: Index 2023 > Gutenberg Index 2022](https://make.wordpress.org/core/handbook/references/keeping-up-with-gutenberg-index/keeping-up-with-gutenberg-index-2022/):
`core/references/keeping-up-with-gutenberg-index/keeping-up-with-gutenberg-index-2022.md`
- [Tutorials & Guides > Running New Contributor Meetings](https://make.wordpress.org/core/handbook/tutorials/running-new-contributor-meetings/):
 `core/tutorials/running-new-contributor-meetings.md`

**Comment by t-hamano** [comment]
Update: ページ数が増えたことにより、マイルストーンを再計算。

2023年内に日本語ハンドブックを公開すると仮定した場合の、毎月の進捗目標概算:

- 3月: 48/92 完了
- 4月: 52/92 完了
- 5月: 58/92 完了
- 6月: 64/92 完了
- 7月: 68/92 完了
- 8月: 74/92 完了
- 9月: 80/92 完了
- 10月: 86/92 完了
- 11月: 92/92 完了
- 12月: WordPressサイトに記事登録、内部リンク書き換え、リリース 🎉

**Comment by t-hamano** [comment]
Update: 作業に遅れあり。

2023/06/09の状況:

- オープンなPRは作業完了と見なさない場合： 44 / 92 完了
- オープンなPRも作業完了と見なす場合： 53 / 92 完了

オープンなPRも作業完了とみなした上で、スケジュールを暫定的に引き直します。

- 2023年6月: 57/92 完了
- 2023年7月: 62/92 完了
- 2023年8月: 67/92 完了
- 2023年9月: 72/92 完了
- 2023年10月: 77/92 完了
- 2023年11月: 82/92 完了
- 2023年12月: 87/92 完了 
- 2024年1月:  92/92 完了
- 2024年2月: WordPressサイトに記事登録、内部リンク書き換え、リリース 🎉

**Comment by t-hamano** [comment]
2023/06/13の状況:

オープンなPRは作業完了と見なさない場合： 44 / 92 完了
オープンなPRも作業完了と見なす場合： 56 / 92 完了

**Comment by t-hamano** [comment]
2023/07/05の状況:

- オープンなPRは作業完了と見なさない場合： 50 / 92 完了
- オープンなPRも作業完了と見なす場合： 57 / 92 完了

**Comment by t-hamano** [comment]
Update: 2023/07/16の状況:

- オープンなPRは作業完了と見なさない場合： 63 / 92 完了
- オープンなPRも作業完了と見なす場合： 64 / 92 完了

- 2023年7月: ✅ 62/92 完了
- 2023年8月: 67/92 完了
- 2023年9月: 72/92 完了
- 2023年10月: 77/92 完了
- 2023年11月: 82/92 完了
- 2023年12月: 87/92 完了 
- 2024年1月:  92/92 完了
- 2024年2月: WordPressサイトに記事登録、内部リンク書き換え、リリース 🎉

**Comment by t-hamano** [comment]
Update: 2023/08/02の状況:

- オープンなPRは作業完了と見なさない場合： 63 / 92 完了
- オープンなPRも作業完了と見なす場合： 64 / 92 完了

各月の目標作業数:

- 2023年8月: 68/92 完了
- 2023年9月: 73/92 完了
- 2023年10月: 78/92 完了
- 2023年11月: 83/92 完了
- 2023年12月: 88/92 完了 
- 2024年1月:  92/92 完了
- 2024年2月: WordPressサイトに記事登録、内部リンク書き換え、リリース 🎉

**Comment by t-hamano** [comment]
Update: 2023/08/02の状況:

#162での原文更新により、以下1ページが追加されました。。

- [Hosting Release Parties](https://make.wordpress.org/core/handbook/about/release-cycle/hosting-release-parties/): core/about/release-cycle/hosting-release-parties.md

- 2023年8月: ✅ 68/93 完了
- 2023年9月: 73/93 完了
- 2023年10月: 78/93 完了
- 2023年11月: 83/93 完了
- 2023年12月: 88/93 完了 
- 2024年1月:  93/93 完了
- 2024年2月: WordPressサイトに記事登録、内部リンク書き換え、リリース 🎉

**Comment by t-hamano** [comment]
Update: 2023/08/23の状況:

75 / 93 完了

目標作業数を少し上回ったので、リリース月を一ヶ月早められるかも

- 2023年8月: 77/93 完了
- 2023年9月: 81/93 完了
- 2023年10月: 85/93 完了
- 2023年11月: 89/93 完了
- 2023年12月: 93/93 完了
- 2024年1月: WordPressサイトに記事登録、内部リンク書き換え、リリース 🎉

**Comment by t-hamano** [comment]
Update: 全ページ翻訳完了も見えてきたので、WordPress.org Japanese Teamにハンドブックとして公開するための管理表を作成。
https://docs.google.com/spreadsheets/d/1aB8iCxetf4SRMr0Ev8FAW1KBEHLARIdZItbrz6d4AAE/edit?usp=sharing

**Comment by t-hamano** [comment]
Update: 2023/08/23の状況:

79 / 93 完了

もう少しだけ作業ペースを上げて、年内リリースを目指してみます。

- 2023年9月: 83/93 完了
- 2023年10月: 88/93 完了
- 2023年11月: 93/93 完了
- 2023年12月: WordPressサイトに記事登録、内部リンク書き換え、リリース 🎉

**Comment by t-hamano** [comment]
Update: 2023/09/13の状況:

87 / 93 完了 (残り6ページ)

早ければ2023年10月内に、遅くとも2023年11月にリリース出来そうです。

**Comment by t-hamano** [comment]
Update: 原文を翻訳する必要はありませんが、コーディング規約関連の9ページを追加。

**Comment by t-hamano** [comment]
全ページの翻訳が完了しましたので、このissueはクローズしたいと思います 🚀
引き続きハンドブックページへの公開作業のため、[タスクリスト](https://github.com/jawordpressorg/core-handbook/issues/192)に取り組んでいきたいと思います。
